name: VPS Setup (Automatic on GitHub)

on:
  push:
    branches:
      - main  # Workflow sẽ tự động chạy mỗi khi bạn push lên nhánh main.

jobs:
  setup-vps:
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu của GitHub Actions.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Kiểm tra mã nguồn từ GitHub repository.

      - name: Cài đặt Python và Flask (hoặc môi trường khác của bạn)
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install flask

      - name: Chạy ứng dụng Flask
        run: |
          echo "from flask import Flask\napp = Flask(__name__)\n@app.route('/')\ndef home():\n    return 'Hello from GitHub Actions!'\nif __name__ == '__main__':\n    app.run(host='0.0.0.0', port=80)" > app.py
          python3 app.py &  # Chạy Flask trong nền

      - name: Tạo Ngrok HTTP Tunnel
        run: |
          # Cài đặt Ngrok (có thể bỏ qua nếu bạn không cần Ngrok)
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          tar -xvzf ngrok-v3-stable-linux-amd64.tgz
          sudo mv ngrok /usr/local/bin

          # Cấu hình với Ngrok auth token
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          
          # Tạo tunnel cho HTTP
          ngrok http 80 > ngrok.log &

          # Đợi cho Ngrok khởi động và lấy URL
          sleep 5
          cat ngrok.log | grep -o "http://[0-9a-zA-Z.:-]*"  # In URL Ngrok ra console

      - name: Kết quả URL Ngrok
        run: |
          echo "Ứng dụng của bạn đang chạy tại: "
          cat ngrok.log | grep -o "http://[0-9a-zA-Z.:-]*"
